const mongoose = require('mongoose')

const jobSchema = new mongoose.Schema(
  {
    title: { type: String, required: true, trim: true },
    company: { type: String, required: true, trim: true },
    companyLogo: { type: String, default: '' },
    department: { type: String, default: '' },
    industry: { type: String, default: '' },
    location: { type: String, required: true },
    locationScope: { type: String, enum: ['India', 'International'], default: 'India' },
    country: { type: String, default: 'India' },
    countryCode: { type: String, default: 'IN' },
    state: { type: String, default: '' },
    stateCode: { type: String, default: '' },
    city: { type: String, default: '' },
    officeAddress: { type: String, default: '' },
    interviewSameAsOffice: { type: Boolean, default: true },
    interviewAddress: { type: String, default: '' },
    salary: { type: String, default: '' },
    experience: { type: String, default: '' },
    type: { type: String, enum: ['Full Time', 'Part Time', 'Contract', 'Freelance'], default: 'Full Time' },
    workMode: { type: String, enum: ['Remote', 'Hybrid', 'On-site'], default: 'Hybrid' },
    posted: { type: String, default: 'Today' },
    deadline: { type: String, default: '' },
    featured: { type: Boolean, default: false },
    urgent: { type: Boolean, default: false },
    skills: [{ type: String }],
    description: { type: String, required: true },
    responsibilities: [{ type: String }],
    requirements: [{ type: String }],
    benefits: [{ type: String }],
    aboutCompany: { type: String, default: '' },
    recruiterEmail: { type: String, default: '', lowercase: true, index: true },
    recruiterName: { type: String, default: '' },
    packageSubscriptionId: { type: mongoose.Schema.Types.ObjectId, ref: 'RecruiterPackageSubscription', default: null },
    packageName: { type: String, default: '' },
    accountDepartmentStatus: { type: String, enum: ['Pending', 'Active', 'Rejected', 'Hold', 'Removed'], default: 'Pending' },
    accountDepartmentRemark: { type: String, default: '' },
    status: { type: String, enum: ['Draft', 'Open', 'Active', 'Closed'], default: 'Open' },
    approval: { type: String, enum: ['Pending', 'Approved', 'Rejected', 'Hold', 'Removed'], default: 'Pending' },
    jobAuthorizedByName: { type: String, default: '' },
    jobAuthorizedByEmail: { type: String, default: '', lowercase: true },
    jobAuthorizedAction: { type: String, default: '' },
    jobAuthorizedRemark: { type: String, default: '' },
    jobAuthorizedAt: { type: Date, default: null },
    applicationsCount: { type: Number, default: 0 },
    views: { type: Number, default: 0 },
  },
  { timestamps: true },
)

module.exports = mongoose.model('Job', jobSchema)
