const faqTopics = [
  ['General', 'How do I create a CromGen Rozgar account?', 'Open the login or register page, choose your account type, enter the required details, and submit the form. Your dashboard opens after successful verification.'],
  ['General', 'Can I use CromGen Rozgar on mobile?', 'Yes. The website is responsive and supports job search, applications, recruiter login, document upload, and account management on mobile browsers.'],
  ['General', 'Is CromGen Rozgar free for candidates?', 'Candidates can browse jobs, create a profile, upload a resume, and apply to eligible jobs without paying a platform fee.'],
  ['General', 'How do I update my profile information?', 'Login to your account, open the profile page, update your details, and save changes. Updated profile data is stored in MongoDB.'],
  ['General', 'Why am I not receiving updates?', 'Check your email address, notification settings, spam folder, and make sure your profile has the correct contact details.'],
  ['Jobs', 'How do I search for jobs?', 'Use the jobs page search, filters, category pages, and company pages to find live approved jobs from MongoDB.'],
  ['Jobs', 'Why is a job not visible publicly?', 'A job appears publicly only when it is active and approved by the account or admin team. Pending, rejected, or closed jobs stay hidden.'],
  ['Jobs', 'How are category job counts calculated?', 'Category counts are calculated dynamically from approved active jobs using job title, industry, department, skills, and work mode signals.'],
  ['Jobs', 'Can I save jobs for later?', 'Candidate dashboards include saved job workflows so you can return to preferred roles without searching again.'],
  ['Jobs', 'How do I know if a job is remote?', 'Each job can show work mode such as Remote, Hybrid, or On-site. Use filters to narrow results by work mode.'],
  ['Applications', 'How do I apply for a job?', 'Open the job details page, review the role, upload or confirm your resume, add required details, and submit the application.'],
  ['Applications', 'Can I apply to the same job twice?', 'Duplicate applications are blocked when the same candidate email applies for the same job or matching job details.'],
  ['Applications', 'Where can I track my application?', 'Login to your candidate dashboard to review submitted applications, saved jobs, interview invites, and alerts.'],
  ['Applications', 'What does application status mean?', 'Application status can move through stages like New, Reviewed, Shortlisted, Interview, Selected, or Rejected based on recruiter action.'],
  ['Applications', 'Can recruiters see my resume?', 'Recruiters can review resumes connected to applications and resume database entries that are available to their role permissions.'],
  ['Candidates', 'How do I upload a resume?', 'Open your profile or the relevant upload flow, choose a PDF file, and submit. The file uploads to Supa Cloud and metadata saves in MongoDB.'],
  ['Candidates', 'Can I update my resume?', 'Yes. When a new resume is uploaded, the previous Supa Cloud file and old MongoDB resume record are cleaned up when the update flow includes the previous resume id.'],
  ['Candidates', 'Which resume file type is accepted?', 'Resume upload accepts PDF files so recruiters can view consistent documents securely.'],
  ['Candidates', 'How is profile strength calculated?', 'Profile strength is based on completed candidate details such as role, skills, experience, resume, and contact information.'],
  ['Candidates', 'Can I edit my skills?', 'Yes. Update your profile skills from your candidate profile. Matching jobs use skill and role signals.'],
  ['Recruiter', 'How do recruiters register?', 'Recruiters open the recruiter register page, enter company and business details, accept policies, create a password, and submit the account.'],
  ['Recruiter', 'Why do recruiters need a business email?', 'Business email verification helps reduce duplicate or personal accounts and keeps recruiter onboarding professional.'],
  ['Recruiter', 'What happens after recruiter registration?', 'New recruiter accounts stay under review until company and document verification is completed by the account team.'],
  ['Recruiter', 'Can recruiters login before approval?', 'Recruiters can login, but dashboard access depends on the verification status and document review stage.'],
  ['Recruiter', 'Why is my recruiter status Review?', 'Review means your account or documents are waiting for account team action before full access is enabled.'],
  ['Recruiter Documents', 'Which documents are required for GST verification?', 'GST verification requires PAN number, GST number, PAN card document, and GST certificate PDF.'],
  ['Recruiter Documents', 'Which documents are required for offer letter verification?', 'Offer letter verification requires PAN number, PAN card document, and offer letter PDF.'],
  ['Recruiter Documents', 'Which documents are required for Aadhar verification?', 'Aadhar verification requires PAN number, PAN document, Aadhar number, and Aadhar card PDF.'],
  ['Recruiter Documents', 'Where are recruiter documents stored?', 'Recruiter documents upload to Supa Cloud document storage and MongoDB stores public URL and metadata.'],
  ['Recruiter Documents', 'What happens if I replace a document?', 'When a document file is replaced, the old Supa Cloud file is deleted and the new file URL is saved.'],
  ['Recruiter Management', 'Who approves recruiters?', 'Admin and account team users can review recruiter profiles, documents, remarks, and approval status from the admin panel.'],
  ['Recruiter Management', 'What statuses can a recruiter have?', 'Recruiter management can use statuses such as Pending, Approved, Rejected, Suspended, and Blocked.'],
  ['Recruiter Management', 'Will recruiter status sync to documents?', 'Status updates from recruiter management sync with recruiter documents and user management where applicable.'],
  ['Recruiter Management', 'Can a blocked recruiter see the reason?', 'When rejected, suspended, or blocked, remarks can be saved and shown to the recruiter during verification review.'],
  ['Recruiter Management', 'Can recruiter data be deleted?', 'Yes. Deleting recruiter records also cleans related document files from Supa Cloud where configured.'],
  ['Admin', 'Where does FAQ data come from?', 'FAQ data is stored in MongoDB and loaded through the backend API. Admin can add, edit, delete, and publish FAQs.'],
  ['Admin', 'Can admin manage categories?', 'Yes. Admin category management creates and updates MongoDB categories that appear on industry and category pages.'],
  ['Admin', 'Can admin manage website branding?', 'Yes. SEO branding stores logo, favicon, names, and metadata in MongoDB, with image assets uploaded to Supa Cloud.'],
  ['Admin', 'Can admin manage social links?', 'Yes. Social media links are managed dynamically and public enabled links are served from MongoDB settings.'],
  ['Admin', 'Can admin manage support messages?', 'Yes. Support messages are saved in MongoDB and can be reviewed from the admin support module.'],
  ['Storage', 'What is Supa Cloud used for?', 'Supa Cloud stores uploaded files such as resumes, recruiter documents, logos, and favicon assets.'],
  ['Storage', 'Why are there separate buckets?', 'Separate buckets or folders keep resumes, recruiter documents, and branding assets organized and easier to clean up.'],
  ['Storage', 'What happens when a file is deleted?', 'The backend deletes the MongoDB record and removes the related Supa Cloud object when storage metadata is available.'],
  ['Storage', 'What happens when a file is updated?', 'The new file uploads first, then the old Supa Cloud file is removed so storage does not keep unnecessary files.'],
  ['Storage', 'Are public URLs saved?', 'When public bucket mode is enabled, the backend saves public file URLs in MongoDB for viewing and rendering.'],
  ['Security', 'Is the Supa Cloud service key public?', 'No. The service role key is used only on the backend and should never be exposed to client-side code.'],
  ['Security', 'How is user access protected?', 'Protected routes use JWT authentication and role authorization for admin, recruiter, hiring, account team, and candidate workflows.'],
  ['Security', 'Can account team access all data?', 'Account team access is scoped to recruiter and job review workflows based on backend authorization.'],
  ['Security', 'Are passwords stored directly?', 'Passwords are hashed before storage and are not returned in user API responses.'],
  ['Security', 'What should I do if login fails?', 'Check your email, password, role-specific login page, and account status. Use reset options if available.'],
  ['Payments', 'Where are recruiter packages managed?', 'Recruiter pricing packages are managed from admin package settings and stored in MongoDB.'],
  ['Payments', 'How does Razorpay work?', 'Razorpay settings and package purchase flows create and verify orders through backend routes.'],
  ['Payments', 'Can packages be changed?', 'Admin can edit package details such as name, price, job limit, validity, discount, and coins.'],
  ['Payments', 'Where are payment logs shown?', 'Payment transaction and log views are available from the admin payment management sections.'],
  ['Payments', 'Can failed payments be reviewed?', 'Payment records can store status and gateway details so admins can review paid, pending, or failed states.'],
  ['Companies', 'How do company profiles appear?', 'Company profiles are generated from active MongoDB recruiter/employer/company records and associated job counts.'],
  ['Companies', 'Can I view jobs by company?', 'Yes. Company detail pages show live approved openings associated with that company.'],
  ['Companies', 'How is company location shown?', 'Company locations are stored from recruiter profile or admin company details and displayed on public company views.'],
  ['Companies', 'Can company details be edited?', 'Recruiter profile and admin company management can update company details based on permission.'],
  ['Companies', 'Why is my company not visible?', 'Company visibility depends on active status, profile details, and available public company profile data.'],
  ['Freelancer', 'Is freelancer data dynamic?', 'Freelancer profiles are stored in MongoDB and served through the freelancer profiles API.'],
  ['Freelancer', 'Can recruiters search freelancers?', 'Recruiters can search freelancer profiles by name, role, location, and skills from recruiter talent pages.'],
  ['Freelancer', 'Who manages freelancer profiles?', 'Admin can manage freelancer profiles from the admin panel and publish active profiles to recruiter views.'],
  ['Freelancer', 'Can freelancer profiles be blocked?', 'Freelancer profile status can be set to Review, Active, Inactive, or Blocked based on admin review.'],
  ['Freelancer', 'Are freelancer projects dynamic?', 'Project and marketplace modules should use MongoDB-backed data where configured through the API.'],
  ['Location', 'Can jobs be posted in India and internationally?', 'Job and recruiter forms support India and selected international country, state, and city combinations.'],
  ['Location', 'How do I choose a recruiter location?', 'During recruiter registration, select India or International, then choose state or region, city, and full address.'],
  ['Location', 'Can admins manage locations?', 'Admin location management stores city, state, country, and status records in MongoDB.'],
  ['Location', 'Why is location required?', 'Location improves job matching, recruiter verification, company display, and candidate search relevance.'],
  ['Location', 'Can remote jobs be posted?', 'Yes. Jobs can use Remote, Hybrid, or On-site work modes.'],
  ['Support', 'How do I contact support?', 'Use the support page, contact page, or support chat form to send your issue with account and contact details.'],
  ['Support', 'What details should I include?', 'Include registered email, phone number, role, issue summary, screenshots if needed, and exact workflow where the issue happened.'],
  ['Support', 'Can support see my application status?', 'Support can help route your issue, but recruiters or hiring teams control application review status.'],
  ['Support', 'How long does recruiter review take?', 'Recruiter account and document reviews are usually handled by the account team after required details are submitted.'],
  ['Support', 'Where can I read policies?', 'Policy pages such as privacy, terms, support, and recruiter policies are available from website footer links.'],
  ['Notifications', 'How do newsletter subscriptions work?', 'Users can subscribe to hiring insights. Subscriber data is stored in MongoDB and managed from admin.'],
  ['Notifications', 'Can admins send updates?', 'Admin can create and send newsletter updates to subscribed users through the hiring insights send flow.'],
  ['Notifications', 'Can I unsubscribe?', 'Subscription status can be updated to unsubscribed from admin or through future unsubscribe workflows.'],
  ['Notifications', 'Do recruiters receive alerts?', 'Recruiter dashboards can show workflow updates for jobs, applications, and package activity where configured.'],
  ['Notifications', 'Do candidates receive job alerts?', 'Candidate dashboards include job alert sections based on saved preferences and matching activity.'],
  ['Data', 'Is data stored in static files?', 'Operational website data should come from MongoDB through backend APIs instead of static frontend data files.'],
  ['Data', 'What happens if MongoDB is not configured?', 'API routes return configuration errors for protected or dynamic data rather than serving stale demo data.'],
  ['Data', 'Can admin export records?', 'Some admin tables include export actions for operational records such as payments or reports.'],
  ['Data', 'Can duplicate records be prevented?', 'Backend validation prevents duplicate recruiter emails, mobile numbers, PAN, GST, Aadhar, and duplicate applications where configured.'],
  ['Data', 'How is old uploaded data cleaned?', 'When supported records are deleted or updated, related Supa Cloud files are removed by backend cleanup hooks.'],
  ['Account Team', 'What can account team manage?', 'Account team can review recruiter accounts, recruiter documents, and job approvals based on allowed role permissions.'],
  ['Account Team', 'Can account team approve jobs?', 'Account team can set job account department status, including active, rejected, hold, or removed with remarks.'],
  ['Account Team', 'Can account team approve documents?', 'Account team can approve, reject, suspend, block, or review recruiter documents where allowed.'],
  ['Account Team', 'Are account team actions tracked?', 'Actions can store reviewer name, email, action, remark, and timestamp for recruiter document and job review workflows.'],
  ['Account Team', 'Do remarks show to recruiters?', 'Remarks for rejected, suspended, blocked, or held records can be shown to recruiters so they know what to correct.'],
  ['Hiring Team', 'What is the hiring team module?', 'Hiring team modules help upload candidate resumes, manage candidate records, and track hiring activity.'],
  ['Hiring Team', 'Where are hiring team resumes stored?', 'Hiring team resume uploads are saved to Supa Cloud resume storage and MongoDB resume records.'],
  ['Hiring Team', 'Can old hiring resumes be replaced?', 'When a hiring team candidate resume is updated, old resume cleanup can remove the previous Supa Cloud file.'],
  ['Hiring Team', 'Can hiring users see applications?', 'Hiring role permissions allow access to candidate, resume, and application workflows configured for that role.'],
  ['Hiring Team', 'Can hiring data be searched?', 'Admin and hiring team tables include search and filter workflows for candidate and resume data.'],
  ['Policies', 'Where are candidate terms shown?', 'Candidate terms are published as MongoDB content pages and rendered from the public terms route.'],
  ['Policies', 'Where are recruiter terms shown?', 'Recruiter terms are published separately under recruiter policy routes and can be opened from recruiter pages.'],
  ['Policies', 'Can policies be edited?', 'Admin policy management can add, edit, publish, and draft policy pages for user and recruiter frontends.'],
  ['Policies', 'Why must recruiters accept terms?', 'Recruiters must accept terms and hiring policies before continuing registration so responsibilities are clear.'],
  ['Policies', 'What if policies change?', 'Admins can update policy pages in MongoDB, and the website will render the latest published version.'],
]

const defaultFaqs = faqTopics.slice(0, 100).map(([category, question, answer], index) => ({
  category,
  question,
  answer,
  status: 'Active',
  sortOrder: index + 1,
  featured: index < 10,
}))

async function ensureDefaultFaqs(Faq, filter = {}) {
  const keys = Object.keys(filter)
  if (keys.length && !(keys.length === 1 && filter.status === 'Active')) return

  await Faq.bulkWrite(
    defaultFaqs.map((faq) => ({
      updateOne: {
        filter: { question: faq.question },
        update: { $setOnInsert: faq },
        upsert: true,
      },
    })),
  )
}

module.exports = { defaultFaqs, ensureDefaultFaqs }
