const express = require('express')
const controllers = require('../controllers/resourceControllers')
const authRoutes = require('./authRoutes')
const crudRoutes = require('./crudRoutes')
const dashboardRoutes = require('./dashboardRoutes')
const gstRoutes = require('./gstRoutes')
const { getRecruiterPage } = require('../controllers/recruiterPageController')
const recruiterPackageRoutes = require('./recruiterPackageRoutes')
const recruiterJobRoutes = require('./recruiterJobRoutes')
const userRoutes = require('./userRoutes')

const router = express.Router()

router.get('/health', (req, res) => res.json({ success: true, message: 'Cromgen Rozgar API is running' }))
router.use('/auth', authRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/gst', gstRoutes)
router.get('/recruiter-page', getRecruiterPage)
router.use('/users', userRoutes)
router.use('/jobs', crudRoutes(controllers.jobs))
router.use('/companies', crudRoutes(controllers.companies))
router.use('/content-pages', crudRoutes(controllers.contentPages))
router.use('/employers', crudRoutes(controllers.employers))
router.use('/faqs', crudRoutes(controllers.faqs))
router.use('/candidates', crudRoutes(controllers.candidates))
router.use('/applications', crudRoutes(controllers.applications))
router.use('/categories', crudRoutes(controllers.categories))
router.use('/locations', crudRoutes(controllers.locations))
router.use('/newsletter-subscribers', crudRoutes(controllers.newsletterSubscribers))
router.use('/payments', crudRoutes(controllers.payments))
router.use('/pricing-packages', crudRoutes(controllers.pricingPackages))
router.use('/recruiter-package-subscriptions', recruiterPackageRoutes)
router.use('/recruiter-job-posts', recruiterJobRoutes)
router.use('/recruiter-documents', crudRoutes(controllers.recruiterDocuments))
router.use('/resumes', crudRoutes(controllers.resumes))
router.use('/settings', crudRoutes(controllers.settings))
router.use('/support-messages', crudRoutes(controllers.supportMessages))
router.use('/testimonials', crudRoutes(controllers.testimonials))

module.exports = router
